FROM php:8.3-apache

RUN cp "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

# Installation des extensions PHP
RUN docker-php-ext-install mysqli pdo pdo_mysql 

# Si vous avez besoin d'activer le module rewrite (courant pour les frameworks PHP)
# RUN a2enmod rewrite && service apache2 restart

# Vous pouvez ajouter d'autres configurations PHP ou Apache icis